# Generated by Django 3.2.5 on 2025-06-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('tag', models.CharField(default='latest', max_length=40)),
                ('description', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Imagen permitida',
                'verbose_name_plural': 'Imágenes permitidas',
                'unique_together': {('name', 'tag')},
            },
        ),
    ]
