# Generated by Django 3.2.5 on 2025-06-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_allowedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='compose',
            field=models.FileField(blank=True, null=True, upload_to='compose_files/'),
        ),
    ]
