# Generated by Django 5.2.4 on 2025-07-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0003_service_compose"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="build_context_dir",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="code",
            field=models.FileField(blank=True, null=True, upload_to="user_code/"),
        ),
        migrations.AddField(
            model_name="service",
            name="env_vars",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="volumes",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
