# Generated by Django 5.2.4 on 2025-11-01 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0004_service_build_context_dir_service_code_and_more"),
        ("paasify", "0026_alter_game_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allowedimage",
            options={
                "ordering": ("name", "tag"),
                "verbose_name": "Imagen permitida",
                "verbose_name_plural": "Imágenes permitidas",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Servicio",
                "verbose_name_plural": "Servicios",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="internal_port",
            field=models.PositiveIntegerField(
                default=80, verbose_name="Puerto interno"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="paasify.sport",
                verbose_name="Asignatura",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="assigned_port",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Puerto asignado"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="build_context_dir",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Directorio de build (tmp)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="code",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="user_code/",
                verbose_name="Código fuente (zip)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="compose",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="compose_files/",
                verbose_name="docker-compose.yml",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="container_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID de contenedor"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
        ),
        migrations.AlterField(
            model_name="service",
            name="dockerfile",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="dockerfiles/",
                verbose_name="Dockerfile",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="env_vars",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Variables de entorno"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.CharField(max_length=200, verbose_name="Imagen"),
        ),
        migrations.AlterField(
            model_name="service",
            name="logs",
            field=models.TextField(blank=True, verbose_name="Logs"),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="service",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Propietario",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="status",
            field=models.CharField(
                default="stopped", max_length=20, verbose_name="Estado"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
        ),
        migrations.AlterField(
            model_name="service",
            name="volumes",
            field=models.JSONField(blank=True, null=True, verbose_name="Volúmenes"),
        ),
    ]
