# Generated by Django 5.1.1 on 2025-11-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0006_alter_allowedimage_options_service_enable_ssh_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="ssh_port",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Puerto SSH"
            ),
        ),
    ]
