# Generated by Django 5.1.1 on 2025-11-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0007_service_ssh_port"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="enable_ssh",
        ),
        migrations.AddField(
            model_name="service",
            name="volume_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nombre del volumen"
            ),
        ),
    ]
