# Generated by Django 5.2.4 on 2025-11-25 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0013_alter_allowedimage_image_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del contenedor')),
                ('container_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Docker')),
                ('status', models.CharField(default='unknown', max_length=20, verbose_name='Estado')),
                ('internal_ports', models.JSONField(blank=True, null=True, verbose_name='Puertos internos')),
                ('assigned_ports', models.JSONField(blank=True, null=True, verbose_name='Puertos asignados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='containers.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Contenedor de Servicio',
                'verbose_name_plural': 'Contenedores de Servicio',
                'ordering': ('service', 'name'),
                'unique_together': {('service', 'name')},
            },
        ),
    ]
