# Generated by Django 5.2.4 on 2026-02-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0016_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='assigned_ports',
            field=models.JSONField(blank=True, help_text='Lista de puertos para servicios docker-compose', null=True, verbose_name='Puertos asignados (compose)'),
        ),
    ]
