# Generated by Django 5.2.4 on 2026-02-04 20:54

import containers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0017_service_assigned_ports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.FileField(blank=True, null=True, upload_to=containers.models.get_code_path, verbose_name='Codigo fuente (zip)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='compose',
            field=models.FileField(blank=True, null=True, upload_to=containers.models.get_compose_path, verbose_name='docker-compose.yml'),
        ),
        migrations.AlterField(
            model_name='service',
            name='dockerfile',
            field=models.FileField(blank=True, null=True, upload_to=containers.models.get_dockerfile_path, verbose_name='Dockerfile'),
        ),
    ]
