# Generated by Django 5.2.4 on 2026-02-04 21:11

import containers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0018_alter_service_code_alter_service_compose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.FileField(blank=True, null=True, upload_to=containers.models.get_service_upload_path, verbose_name='Codigo fuente (zip)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='compose',
            field=models.FileField(blank=True, null=True, upload_to=containers.models.get_service_upload_path, verbose_name='docker-compose.yml'),
        ),
        migrations.AlterField(
            model_name='service',
            name='dockerfile',
            field=models.FileField(blank=True, null=True, upload_to=containers.models.get_service_upload_path, verbose_name='Dockerfile'),
        ),
    ]
