# Generated by Django 5.2.4 on 2026-02-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0021_service_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='container_configs',
            field=models.JSONField(blank=True, null=True, verbose_name='Configuración de contenedores'),
        ),
        migrations.AddField(
            model_name='servicecontainer',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Imagen'),
        ),
    ]
