# Generated by Django 5.2.4 on 2026-02-24 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0022_service_container_configs_and_more'),
        ('paasify', '0043_alter_userproject_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='paasify.userproject', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='service',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='paasify.subject', verbose_name='Asignatura'),
        ),
    ]
