# Generated by Django 5.1.1 on 2025-11-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "containers",
            "0005_alter_allowedimage_options_alter_service_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allowedimage",
            options={
                "ordering": ("name", "tag"),
                "verbose_name": "Imagen permitida",
                "verbose_name_plural": "Imagenes permitidas",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="enable_ssh",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="service",
            name="code",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="user_code/",
                verbose_name="Codigo fuente (zip)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="volumes",
            field=models.JSONField(blank=True, null=True, verbose_name="Volumenes"),
        ),
    ]
