# Generated by Django 5.1.1 on 2025-11-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0008_remove_service_enable_ssh_service_volume_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="ssh_password",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Clave SSH",
            ),
        ),
    ]
