# Generated by Django 5.2.4 on 2025-11-20 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0010_service_enable_ssh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='enable_ssh',
        ),
        migrations.RemoveField(
            model_name='service',
            name='ssh_password',
        ),
        migrations.RemoveField(
            model_name='service',
            name='ssh_port',
        ),
    ]
