# Generated by Django 5.1.1 on 2026-02-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0019_alter_service_code_alter_service_compose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='container_type',
            field=models.CharField(default='misc', max_length=20, verbose_name='Tipo de contenedor'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_web',
            field=models.BooleanField(default=True, verbose_name='¿Es una web accesible?'),
        ),
        migrations.AddField(
            model_name='servicecontainer',
            name='container_type',
            field=models.CharField(default='misc', max_length=20, verbose_name='Tipo de contenedor'),
        ),
        migrations.AddField(
            model_name='servicecontainer',
            name='is_web',
            field=models.BooleanField(default=False, verbose_name='¿Es una web accesible?'),
        ),
    ]
