# Generated by Django 5.1.1 on 2026-02-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0020_service_container_type_service_is_web_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='mode',
            field=models.CharField(choices=[('default', 'Catálogo Oficial'), ('dockerhub', 'DockerHub'), ('custom', 'Personalizado')], default='default', max_length=20, verbose_name='Modo de despliegue'),
        ),
    ]
