# Generated by Django 5.2.4 on 2026-03-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0023_alter_service_project_alter_service_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subdomain',
            field=models.CharField(blank=True, editable=False, help_text='Subdominio único generado para acceso web.', max_length=120, null=True, unique=True, verbose_name='Subdominio'),
        ),
        migrations.AddField(
            model_name='servicecontainer',
            name='subdomain',
            field=models.CharField(blank=True, editable=False, help_text='Subdominio específico para este contenedor (solo en Compose).', max_length=150, null=True, unique=True, verbose_name='Subdominio'),
        ),
    ]
