# Imagen base: Python
FROM python:3.12-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo de aplicación
COPY app.py .

# Instalar dependencias necesarias
RUN pip install --no-cache-dir flask

# Variable de entorno
ENV FLASK_RUN_HOST=0.0.0.0

# Exponer el puerto 5000
EXPOSE 5000

# Comando de arranque
CMD ["flask", "--app", "app.py", "run"]
