# Generated by Django 5.1.5 on 2025-02-10 00:10

import colorfield.fields
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('gold', models.IntegerField(default=0, verbose_name='Oro')),
                ('silver', models.IntegerField(default=0, verbose_name='Plata')),
                ('bronze', models.IntegerField(default=0, verbose_name='Bronce')),
                ('cuarto', models.IntegerField(default=0, verbose_name='4 lugar')),
                ('quinto', models.IntegerField(default=0, verbose_name='5to lugar')),
                ('sexto', models.IntegerField(default=0, verbose_name='6to lugar')),
                ('color', colorfield.fields.ColorField(default='#ff0000', image_field=None, max_length=25, samples=None, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'db_table': 'faculty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre y apellidos')),
                ('year', models.CharField(max_length=100, verbose_name='Email')),
                ('sexo', models.CharField(choices=[('Masculino', 'M'), ('Femenino', 'F')], max_length=100, verbose_name='sexo')),
            ],
            options={
                'verbose_name': 'Gestión de Alumno',
                'verbose_name_plural': 'Gestión de Alumnos',
                'db_table': 'player',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('players', models.CharField(max_length=100, verbose_name='Profesor Asignado')),
                ('genero', models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=100, verbose_name='Año')),
                ('category', models.CharField(choices=[('Asignatura obligatorias', 'Asignatura obligatorias'), ('Asignatura optativa', 'Asignatura optativa'), ('Asignatura electiva', 'Asignatura electiva')], max_length=100, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Gestión de Asignatura',
                'verbose_name_plural': 'Gestión de Asignaturas',
                'db_table': 'sport',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Nombre del Proyecto')),
                ('student', models.CharField(default='Sin asignar', max_length=100, verbose_name='Alumno Asignado')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('time', models.TimeField(default=datetime.time(19, 10, 55, 78792), verbose_name='Hora')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paasify.sport', verbose_name='Asignatura Asociada')),
            ],
            options={
                'verbose_name': 'Gestión de Proyecto',
                'verbose_name_plural': 'Gestión de Proyectos',
                'db_table': 'game',
                'managed': True,
            },
        ),
    ]
