# Generated by Django 5.1.5 on 2025-03-25 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0012_remove_unused_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.time(23, 32, 43, 684883), verbose_name='Hora'),
        ),
    ]
