# Generated by Django 5.2.4 on 2025-07-29 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0023_alter_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.time(19, 26, 44, 131698), verbose_name='Hora'),
        ),
    ]
