# Generated by Django 5.2.7 on 2025-11-04 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0027_alter_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.time(22, 58, 13, 546406), verbose_name='Hora'),
        ),
    ]
