# Generated by Django 5.2.7 on 2025-11-04 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0028_alter_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.time(23, 7, 40, 352254), verbose_name='Hora'),
        ),
    ]
