# Generated by Django 5.1.1 on 2025-11-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0033_remove_sexo_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': True, 'verbose_name': 'Perfil de alumno', 'verbose_name_plural': 'Perfiles de alumnos'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('Asignatura obligatorias', 'Asignatura obligatorias'), ('Asignatura optativa', 'Asignatura optativa'), ('Asignatura electiva', 'Asignatura electiva')], max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='genero',
            field=models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=100, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='players',
            field=models.CharField(max_length=100, verbose_name='Profesor asignado'),
        ),
    ]
