# Generated by Django 5.2.4 on 2025-11-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0034_alter_userprofile_options_alter_subject_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_token',
            field=models.TextField(blank=True, help_text='Token JWT para autenticacion en API. Se genera automaticamente.', null=True, verbose_name='Token API (JWT)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token_created_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se genero el token actual.', null=True, verbose_name='Fecha creacion token'),
        ),
    ]
