# Generated by Django 5.2.4 on 2026-02-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0037_expiringtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre y apellidos'),
        ),
    ]
