# Generated by Django 5.2.4 on 2026-02-22 21:35

import paasify.models.SubjectModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0039_subject_color_subject_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=paasify.models.SubjectModel.get_logo_upload_path, verbose_name='Logo de la asignatura'),
        ),
    ]
