# Generated by Django 5.2.4 on 2026-02-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0040_alter_subject_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Si está marcado, se obligará al usuario a cambiar su contraseña en el próximo inicio de sesión.', verbose_name='Debe cambiar contraseña'),
        ),
    ]
