# Generated by Django 5.2.4 on 2026-03-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0043_alter_userproject_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='genero',
            field=models.CharField(max_length=100, verbose_name='Año'),
        ),
    ]
