server {
    listen 80;
    server_name paas.tfg.etsii.urjc.es;
    
    # Redireccionar todo el tráfico HTTP a HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name paas.tfg.etsii.urjc.es;

    # Certificados SSL (se montarán en /etc/nginx/certs)
    ssl_certificate /etc/nginx/certs/paas.tfg.etsii.urjc.es.crt;
    ssl_certificate_key /etc/nginx/certs/paas.tfg.etsii.urjc.es.key;
    
    # Opciones de seguridad SSL recomendadas
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # 1. Aplicación Principal (PaaSify)
    location / {
        proxy_pass http://paasify_core:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSockets support (para Daphne)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # 2. Monitorización (cAdvisor) protegido por usuario y contraseña
    location /monitorizacion/ {
        auth_basic "Restricted Access";
        # auth_basic_user_file: Se mapeará un archivo generado con htpasswd
        auth_basic_user_file /etc/nginx/htpasswd/.htpasswd;
        
        proxy_pass http://paasify_cadvisor:8080;
        proxy_redirect default;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 3. Archivos estáticos de Django
    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
    }

    # 4. Archivos media/subidos
    location /media/ {
        alias /app/media/;
        expires 30d;
    }
}
