# Generated by Django 5.1.5 on 2025-02-10 03:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paasify.player', verbose_name='Alumno Asignado'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.time(22, 57, 54, 7621), verbose_name='Hora'),
        ),
    ]
