# Generated by Django 5.1.5 on 2025-03-24 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0002_alter_game_student_alter_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.time(16, 10, 22, 297606), verbose_name='Hora'),
        ),
    ]
