# Generated by Django 5.1.5 on 2025-03-25 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0004_alter_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.time(20, 39, 44, 682123), verbose_name='Hora'),
        ),
    ]
