# Generated by Django 5.1.5 on 2025-03-25 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0005_alter_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.time(21, 1, 57, 492090), verbose_name='Hora'),
        ),
    ]
