# Generated by Django 5.1.5 on 2025-03-25 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0006_alter_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.time(21, 43, 45, 843555), verbose_name='Hora'),
        ),
    ]
