# Generated by Django 5.1.5 on 2025-03-25 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0008_alter_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.time(22, 45, 27, 199042), verbose_name='Hora'),
        ),
    ]
