# Generated by Django 5.1.5 on 2025-03-25 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0009_alter_game_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.time(23, 9, 21, 750106), verbose_name='Hora'),
        ),
    ]
