# Generated by Django 5.1.5 on 2025-03-25 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0013_alter_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.time(23, 41, 24, 993667), verbose_name='Hora'),
        ),
    ]
