# Generated by Django 5.1.5 on 2025-03-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0014_alter_game_time'),
    ]

    operations = [
    ]
