# Generated by Django 5.1.5 on 2025-03-25 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0016_remove_faculty_permissions_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.time(23, 45, 46, 333554), verbose_name='Hora'),
        ),
    ]
