# Generated by Django 5.1.5 on 2025-03-27 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0019_remove_faculty_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.time(23, 26, 59, 778421), verbose_name='Hora'),
        ),
    ]
