# Generated by Django 3.2.5 on 2025-06-13 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0020_alter_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.time(23, 3, 58, 30351), verbose_name='Hora'),
        ),
    ]
