# Generated by Django 5.2.4 on 2025-07-22 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paasify", "0021_alter_game_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="time",
            field=models.TimeField(
                default=datetime.time(0, 17, 12, 91766), verbose_name="Hora"
            ),
        ),
    ]
