# Generated by Django 5.2.4 on 2025-07-29 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0022_alter_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.time(17, 31, 34, 270804), verbose_name='Hora'),
        ),
    ]
