# Generated by Django 5.2.4 on 2025-11-01 15:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paasify", "0024_alter_game_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={
                "managed": True,
                "ordering": ("-date", "-time"),
                "verbose_name": "Gestión de Proyecto",
                "verbose_name_plural": "Gestión de Proyectos",
            },
        ),
        migrations.AlterModelOptions(
            name="player",
            options={
                "managed": True,
                "verbose_name": "Alumno",
                "verbose_name_plural": "Alumnos",
            },
        ),
        migrations.AddField(
            model_name="player",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario (auth)",
            ),
        ),
        migrations.AddField(
            model_name="sport",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="subjects_as_student",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Alumnos matriculados (usuarios)",
            ),
        ),
        migrations.AddField(
            model_name="sport",
            name="teacher_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects_as_teacher",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Profesor asignado (usuario)",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="sport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="projects",
                to="paasify.sport",
                verbose_name="Asignatura Asociada",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="projects",
                to="paasify.player",
                verbose_name="Alumno Asignado",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="time",
            field=models.TimeField(
                default=datetime.time(16, 19, 3, 228815), verbose_name="Hora"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nombre",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Nombre y apellidos"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="sexo",
            field=models.CharField(
                choices=[("Masculino", "M"), ("Femenino", "F")],
                max_length=100,
                verbose_name="Sexo",
            ),
        ),
    ]
