# Generated by Django 5.2.4 on 2025-11-01 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "paasify",
            "0025_alter_game_options_alter_player_options_player_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="time",
            field=models.TimeField(
                default=datetime.time(16, 19, 14, 33906), verbose_name="Hora"
            ),
        ),
    ]
