# Generated by Django 5.2.4 on 2025-11-03 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0026_alter_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.time(19, 43, 3, 718891), verbose_name='Hora'),
        ),
    ]
