# Generated by Django 5.1.1 on 2025-11-29 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0035_userprofile_api_token_userprofile_token_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Perfil de profesor',
                'verbose_name_plural': 'Perfiles de profesores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('paasify.userprofile',),
        ),
    ]
