# Generated by Django 5.1.1 on 2026-02-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0038_alter_userprofile_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#4e73df', max_length=7, verbose_name='Color de la asignatura'),
        ),
        migrations.AddField(
            model_name='subject',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo de la asignatura'),
        ),
    ]
