# Generated by Django 5.1.1 on 2026-02-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0041_userprofile_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='genero',
            field=models.CharField(max_length=100, verbose_name='Ano'),
        ),
    ]
