# Generated by Django 5.2.4 on 2026-02-24 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paasify', '0042_alter_subject_category_alter_subject_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='paasify.subject', verbose_name='Asignatura Asociada'),
        ),
    ]
